[package]
name = "mnist_predictor"
version = "0.3.0"
authors = ["zetanumbers <zeta0.114942@gmail.com>"]
edition = "2018"

[lib]
name = "mnist_predictor"
crate-type = ["cdylib"]

[dependencies]
tokio = { version = "0.2", features = ["tcp", "rt-core", "rt-threaded", "io-util", "fs", "sync"] }
